apiVersion: v1
kind: Service
metadata:
  name: restaurant-rating-service
spec:
  type: NodePort
  selector:
    app: restaurant-rating-app
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081
